Word --> ConsonantsI VowelsF
Word --> ConsonantsI RhymeF
Word --> Vowels ConsonantsF
Word --> SyllI Sylls
Word --> Vowel Vowels
Sylls --> SepSyll Sylls
Sylls --> Separator SyllF
SepSyll --> Separator Syll
Syll --> Vowel Vowels
Syll --> Vowels ConsonantsC
Syll --> ConsonantsO Vowels
Syll --> ConsonantsO Rhyme
SyllI --> ConsonantsI Vowels
SyllI --> ConsonantsI Rhyme
SyllI --> Vowel Vowels
SyllI --> Vowels ConsonantsC
SyllF --> Vowels ConsonantsF
SyllF --> Vowel Vowels
SyllF --> ConsonantsO VowelsF
SyllF --> ConsonantsO RhymeF
Rhyme --> Vowels ConsonantsC
RhymeF --> Vowels ConsonantsF
VowelsF --> VowelF VowelsF
Vowels --> Vowel Vowels
ConsonantsI --> ConsonantI ConsonantsI
ConsonantsO --> ConsonantO ConsonantsO
ConsonantsC --> ConsonantC ConsonantsC
ConsonantsF --> ConsonantF ConsonantsF
Separator --> -
Word --> a
Word --> i
Word --> y
Word --> o
Word --> O
Word --> e
Word --> E
Word --> )
Word --> 2
Word --> 9
Word --> 5
Word --> 1
Word --> @
Word --> (
Word --> 3
Word --> j
Word --> 8
Word --> w
Word --> u
VowelF --> a
VowelF --> i
VowelF --> y
VowelF --> o
VowelF --> O
VowelF --> e
VowelF --> E
VowelF --> )
VowelF --> 2
VowelF --> 9
VowelF --> 5
VowelF --> 1
VowelF --> @
VowelF --> (
VowelF --> 3
VowelF --> j
VowelF --> 8
VowelF --> w
VowelF --> u
VowelsF --> a
VowelsF --> i
VowelsF --> y
VowelsF --> o
VowelsF --> O
VowelsF --> e
VowelsF --> E
VowelsF --> )
VowelsF --> 2
VowelsF --> 9
VowelsF --> 5
VowelsF --> 1
VowelsF --> @
VowelsF --> (
VowelsF --> 3
VowelsF --> j
VowelsF --> 8
VowelsF --> w
VowelsF --> u
Syll --> a
Syll --> i
Syll --> y
Syll --> o
Syll --> O
Syll --> e
Syll --> E
Syll --> )
Syll --> 2
Syll --> 9
Syll --> 5
Syll --> 1
Syll --> @
Syll --> (
Syll --> 3
Syll --> j
Syll --> 8
Syll --> w
Syll --> u
ConsonantI --> p
ConsonantI --> b
ConsonantI --> t
ConsonantI --> d
ConsonantI --> k
ConsonantI --> g
ConsonantI --> f
ConsonantI --> v
ConsonantI --> s
ConsonantI --> S
ConsonantI --> Z
ConsonantI --> m
ConsonantI --> n
ConsonantI --> N
ConsonantI --> l
ConsonantI --> R
ConsonantI --> G
ConsonantI --> z
ConsonantF --> p
ConsonantF --> b
ConsonantF --> t
ConsonantF --> d
ConsonantF --> k
ConsonantF --> g
ConsonantF --> f
ConsonantF --> v
ConsonantF --> s
ConsonantF --> S
ConsonantF --> Z
ConsonantF --> m
ConsonantF --> n
ConsonantF --> N
ConsonantF --> l
ConsonantF --> R
ConsonantF --> G
ConsonantF --> z
Vowel --> a
Vowel --> i
Vowel --> y
Vowel --> o
Vowel --> O
Vowel --> e
Vowel --> E
Vowel --> )
Vowel --> 2
Vowel --> 9
Vowel --> 5
Vowel --> 1
Vowel --> @
Vowel --> (
Vowel --> 3
Vowel --> j
Vowel --> 8
Vowel --> w
Vowel --> u
ConsonantsI --> p
ConsonantsI --> b
ConsonantsI --> t
ConsonantsI --> d
ConsonantsI --> k
ConsonantsI --> g
ConsonantsI --> f
ConsonantsI --> v
ConsonantsI --> s
ConsonantsI --> S
ConsonantsI --> Z
ConsonantsI --> m
ConsonantsI --> n
ConsonantsI --> N
ConsonantsI --> l
ConsonantsI --> R
ConsonantsI --> z
ConsonantsI --> G
ConsonantsF --> p
ConsonantsF --> b
ConsonantsF --> t
ConsonantsF --> d
ConsonantsF --> k
ConsonantsF --> g
ConsonantsF --> f
ConsonantsF --> v
ConsonantsF --> s
ConsonantsF --> S
ConsonantsF --> Z
ConsonantsF --> m
ConsonantsF --> n
ConsonantsF --> N
ConsonantsF --> l
ConsonantsF --> R
ConsonantsF --> G
ConsonantsF --> z
Vowels --> a
Vowels --> i
Vowels --> y
Vowels --> o
Vowels --> O
Vowels --> e
Vowels --> E
Vowels --> )
Vowels --> 2
Vowels --> 9
Vowels --> 5
Vowels --> 1
Vowels --> @
Vowels --> (
Vowels --> 3
Vowels --> j
Vowels --> 8
Vowels --> w
Vowels --> u
SyllI --> a
SyllI --> i
SyllI --> y
SyllI --> o
SyllI --> O
SyllI --> e
SyllI --> E
SyllI --> )
SyllI --> 2
SyllI --> 9
SyllI --> 5
SyllI --> 1
SyllI --> @
SyllI --> (
SyllI --> 3
SyllI --> j
SyllI --> 8
SyllI --> w
SyllI --> u
SyllF --> a
SyllF --> i
SyllF --> y
SyllF --> o
SyllF --> O
SyllF --> e
SyllF --> E
SyllF --> )
SyllF --> 2
SyllF --> 9
SyllF --> 5
SyllF --> 1
SyllF --> @
SyllF --> (
SyllF --> 3
SyllF --> j
SyllF --> 8
SyllF --> w
SyllF --> u
ConsonantO --> p
ConsonantO --> b
ConsonantO --> t
ConsonantO --> d
ConsonantO --> k
ConsonantO --> g
ConsonantO --> f
ConsonantO --> v
ConsonantO --> s
ConsonantO --> S
ConsonantO --> Z
ConsonantO --> m
ConsonantO --> n
ConsonantO --> N
ConsonantO --> l
ConsonantO --> R
ConsonantO --> G
ConsonantO --> z
ConsonantC --> p
ConsonantC --> b
ConsonantC --> t
ConsonantC --> d
ConsonantC --> k
ConsonantC --> g
ConsonantC --> f
ConsonantC --> v
ConsonantC --> s
ConsonantC --> S
ConsonantC --> Z
ConsonantC --> m
ConsonantC --> n
ConsonantC --> N
ConsonantC --> l
ConsonantC --> R
ConsonantC --> G
ConsonantC --> z
ConsonantsO --> p
ConsonantsO --> b
ConsonantsO --> t
ConsonantsO --> d
ConsonantsO --> k
ConsonantsO --> g
ConsonantsO --> f
ConsonantsO --> v
ConsonantsO --> s
ConsonantsO --> S
ConsonantsO --> Z
ConsonantsO --> m
ConsonantsO --> n
ConsonantsO --> N
ConsonantsO --> l
ConsonantsO --> R
ConsonantsO --> G
ConsonantsO --> z
ConsonantsC --> p
ConsonantsC --> b
ConsonantsC --> t
ConsonantsC --> d
ConsonantsC --> k
ConsonantsC --> g
ConsonantsC --> f
ConsonantsC --> v
ConsonantsC --> s
ConsonantsC --> S
ConsonantsC --> Z
ConsonantsC --> m
ConsonantsC --> n
ConsonantsC --> N
ConsonantsC --> l
ConsonantsC --> R
ConsonantsC --> G
ConsonantsC --> z