Word --> ConsonantsI VowelsF
Word --> ConsonantsI RhymeF
Word --> Vowels ConsonantsF
Word --> SyllI Sylls
Word --> Vowel Vowels
Sylls --> SepSyll Sylls
Sylls --> Separator SyllF
SepSyll --> Separator Syll
Syll --> Vowel Vowels
Syll --> Vowels ConsonantsC
Syll --> ConsonantsO Vowels
Syll --> ConsonantsO Rhyme
SyllI --> ConsonantsI Vowels
SyllI --> ConsonantsI Rhyme
SyllI --> Vowel Vowels
SyllI --> Vowels ConsonantsC
SyllF --> Vowels ConsonantsF
SyllF --> Vowel Vowels
SyllF --> ConsonantsO VowelsF
SyllF --> ConsonantsO RhymeF
Rhyme --> Vowels ConsonantsC
RhymeF --> Vowels ConsonantsF
VowelsF --> VowelF VowelsF
Vowels --> Vowel Vowels
ConsonantsI --> ConsonantI ConsonantsI
ConsonantsO --> ConsonantO ConsonantsO
ConsonantsC --> ConsonantC ConsonantsC
ConsonantsF --> ConsonantF ConsonantsF
Separator --> -
Word --> q
Word --> U
Word --> 5
Word --> E
Word --> $
Word --> Q
Word --> P
Word --> c
Word --> u
Word --> H
Word --> {
Word --> i
Word --> 1
Word --> 3
Word --> ~
Word --> #
Word --> V
Word --> @
Word --> I
VowelF --> q
VowelF --> U
VowelF --> 5
VowelF --> E
VowelF --> $
VowelF --> Q
VowelF --> P
VowelF --> c
VowelF --> u
VowelF --> H
VowelF --> {
VowelF --> i
VowelF --> 1
VowelF --> 3
VowelF --> ~
VowelF --> #
VowelF --> V
VowelF --> @
VowelF --> I
VowelsF --> q
VowelsF --> U
VowelsF --> 5
VowelsF --> E
VowelsF --> $
VowelsF --> Q
VowelsF --> P
VowelsF --> c
VowelsF --> u
VowelsF --> H
VowelsF --> {
VowelsF --> i
VowelsF --> 1
VowelsF --> 3
VowelsF --> ~
VowelsF --> #
VowelsF --> V
VowelsF --> @
VowelsF --> I
Syll --> q
Syll --> U
Syll --> 5
Syll --> E
Syll --> $
Syll --> Q
Syll --> P
Syll --> c
Syll --> u
Syll --> H
Syll --> {
Syll --> i
Syll --> 1
Syll --> 3
Syll --> ~
Syll --> #
Syll --> V
Syll --> @
Syll --> I
ConsonantI --> T
ConsonantI --> R
ConsonantI --> r
ConsonantI --> l
ConsonantI --> j
ConsonantI --> C
ConsonantI --> v
ConsonantI --> N
ConsonantI --> m
ConsonantI --> Z
ConsonantI --> F
ConsonantI --> x
ConsonantI --> b
ConsonantI --> h
ConsonantI --> z
ConsonantI --> n
ConsonantI --> g
ConsonantI --> k
ConsonantI --> t
ConsonantI --> d
ConsonantI --> D
ConsonantI --> f
ConsonantI --> s
ConsonantI --> p
ConsonantI --> S
ConsonantI --> _
ConsonantI --> w
ConsonantI --> J
ConsonantF --> T
ConsonantF --> R
ConsonantF --> r
ConsonantF --> l
ConsonantF --> j
ConsonantF --> C
ConsonantF --> v
ConsonantF --> N
ConsonantF --> m
ConsonantF --> Z
ConsonantF --> F
ConsonantF --> x
ConsonantF --> b
ConsonantF --> h
ConsonantF --> z
ConsonantF --> n
ConsonantF --> g
ConsonantF --> k
ConsonantF --> t
ConsonantF --> d
ConsonantF --> D
ConsonantF --> f
ConsonantF --> s
ConsonantF --> p
ConsonantF --> S
ConsonantF --> _
ConsonantF --> w
ConsonantF --> J
Vowel --> q
Vowel --> U
Vowel --> 5
Vowel --> E
Vowel --> $
Vowel --> Q
Vowel --> P
Vowel --> c
Vowel --> u
Vowel --> H
Vowel --> {
Vowel --> i
Vowel --> 1
Vowel --> 3
Vowel --> ~
Vowel --> #
Vowel --> V
Vowel --> @
Vowel --> I
ConsonantsI --> T
ConsonantsI --> R
ConsonantsI --> r
ConsonantsI --> l
ConsonantsI --> j
ConsonantsI --> C
ConsonantsI --> v
ConsonantsI --> N
ConsonantsI --> m
ConsonantsI --> Z
ConsonantsI --> F
ConsonantsI --> x
ConsonantsI --> b
ConsonantsI --> h
ConsonantsI --> z
ConsonantsI --> n
ConsonantsI --> g
ConsonantsI --> k
ConsonantsI --> t
ConsonantsI --> d
ConsonantsI --> D
ConsonantsI --> f
ConsonantsI --> s
ConsonantsI --> p
ConsonantsI --> S
ConsonantsI --> _
ConsonantsI --> w
ConsonantsI --> J
ConsonantsF --> T
ConsonantsF --> R
ConsonantsF --> r
ConsonantsF --> l
ConsonantsF --> j
ConsonantsF --> C
ConsonantsF --> v
ConsonantsF --> N
ConsonantsF --> m
ConsonantsF --> Z
ConsonantsF --> F
ConsonantsF --> x
ConsonantsF --> b
ConsonantsF --> h
ConsonantsF --> z
ConsonantsF --> n
ConsonantsF --> g
ConsonantsF --> k
ConsonantsF --> t
ConsonantsF --> d
ConsonantsF --> D
ConsonantsF --> f
ConsonantsF --> s
ConsonantsF --> p
ConsonantsF --> S
ConsonantsF --> _
ConsonantsF --> w
ConsonantsF --> J
Vowels --> q
Vowels --> U
Vowels --> 5
Vowels --> E
Vowels --> $
Vowels --> Q
Vowels --> P
Vowels --> c
Vowels --> u
Vowels --> H
Vowels --> {
Vowels --> i
Vowels --> 1
Vowels --> 3
Vowels --> ~
Vowels --> #
Vowels --> V
Vowels --> @
Vowels --> I
SyllI --> q
SyllI --> U
SyllI --> 5
SyllI --> E
SyllI --> $
SyllI --> Q
SyllI --> P
SyllI --> c
SyllI --> u
SyllI --> H
SyllI --> {
SyllI --> i
SyllI --> 1
SyllI --> 3
SyllI --> ~
SyllI --> #
SyllI --> V
SyllI --> @
SyllI --> I
SyllF --> q
SyllF --> U
SyllF --> 5
SyllF --> E
SyllF --> $
SyllF --> Q
SyllF --> P
SyllF --> c
SyllF --> u
SyllF --> H
SyllF --> {
SyllF --> i
SyllF --> 1
SyllF --> 3
SyllF --> ~
SyllF --> #
SyllF --> V
SyllF --> @
SyllF --> I
ConsonantO --> T
ConsonantO --> R
ConsonantO --> r
ConsonantO --> l
ConsonantO --> j
ConsonantO --> C
ConsonantO --> v
ConsonantO --> N
ConsonantO --> m
ConsonantO --> Z
ConsonantO --> F
ConsonantO --> x
ConsonantO --> b
ConsonantO --> h
ConsonantO --> z
ConsonantO --> n
ConsonantO --> g
ConsonantO --> k
ConsonantO --> t
ConsonantO --> d
ConsonantO --> D
ConsonantO --> f
ConsonantO --> s
ConsonantO --> p
ConsonantO --> S
ConsonantO --> _
ConsonantO --> w
ConsonantO --> J
ConsonantC --> T
ConsonantC --> R
ConsonantC --> r
ConsonantC --> l
ConsonantC --> j
ConsonantC --> C
ConsonantC --> v
ConsonantC --> N
ConsonantC --> m
ConsonantC --> Z
ConsonantC --> F
ConsonantC --> x
ConsonantC --> b
ConsonantC --> h
ConsonantC --> z
ConsonantC --> n
ConsonantC --> g
ConsonantC --> k
ConsonantC --> t
ConsonantC --> d
ConsonantC --> D
ConsonantC --> f
ConsonantC --> s
ConsonantC --> p
ConsonantC --> S
ConsonantC --> _
ConsonantC --> w
ConsonantC --> J
ConsonantsO --> T
ConsonantsO --> R
ConsonantsO --> r
ConsonantsO --> l
ConsonantsO --> j
ConsonantsO --> C
ConsonantsO --> v
ConsonantsO --> N
ConsonantsO --> m
ConsonantsO --> Z
ConsonantsO --> F
ConsonantsO --> x
ConsonantsO --> b
ConsonantsO --> h
ConsonantsO --> z
ConsonantsO --> n
ConsonantsO --> g
ConsonantsO --> k
ConsonantsO --> t
ConsonantsO --> d
ConsonantsO --> D
ConsonantsO --> f
ConsonantsO --> s
ConsonantsO --> p
ConsonantsO --> S
ConsonantsO --> _
ConsonantsO --> w
ConsonantsO --> J
ConsonantsC --> T
ConsonantsC --> R
ConsonantsC --> r
ConsonantsC --> l
ConsonantsC --> j
ConsonantsC --> C
ConsonantsC --> v
ConsonantsC --> N
ConsonantsC --> m
ConsonantsC --> Z
ConsonantsC --> F
ConsonantsC --> x
ConsonantsC --> b
ConsonantsC --> h
ConsonantsC --> z
ConsonantsC --> n
ConsonantsC --> g
ConsonantsC --> k
ConsonantsC --> t
ConsonantsC --> d
ConsonantsC --> D
ConsonantsC --> f
ConsonantsC --> s
ConsonantsC --> p
ConsonantsC --> S
ConsonantsC --> _
ConsonantsC --> w
ConsonantsC --> J