Word --> ConsonantsI VowelsF
Word --> ConsonantsI RhymeF
Word --> Vowels ConsonantsF
Word --> SyllI Sylls
Word --> Vowel Vowels
Sylls --> SepSyll Sylls
Sylls --> Separator SyllF
SepSyll --> Separator Syll
Syll --> Vowel Vowels
Syll --> Vowels ConsonantsC
Syll --> ConsonantsO Vowels
Syll --> ConsonantsO Rhyme
SyllI --> ConsonantsI Vowels
SyllI --> ConsonantsI Rhyme
SyllI --> Vowel Vowels
SyllI --> Vowels ConsonantsC
SyllF --> Vowels ConsonantsF
SyllF --> Vowel Vowels
SyllF --> ConsonantsO VowelsF
SyllF --> ConsonantsO RhymeF
Rhyme --> Vowels ConsonantsC
RhymeF --> Vowels ConsonantsF
VowelsF --> VowelF VowelsF
Vowels --> Vowel Vowels
ConsonantsI --> ConsonantI ConsonantsI
ConsonantsO --> ConsonantO ConsonantsO
ConsonantsC --> ConsonantC ConsonantsC
ConsonantsF --> ConsonantF ConsonantsF
Separator --> -
Word --> i
Word --> a
Word --> u
Word --> y
Word --> )
Word --> e
Word --> |
Word --> o
Word --> I
Word --> Y
Word --> E
Word --> /
Word --> &
Word --> O
Word --> U
Word --> @
VowelF --> i
VowelF --> a
VowelF --> u
VowelF --> y
VowelF --> )
VowelF --> e
VowelF --> |
VowelF --> o
VowelF --> I
VowelF --> Y
VowelF --> E
VowelF --> /
VowelF --> &
VowelF --> O
VowelF --> U
VowelF --> @
VowelsF --> i
VowelsF --> a
VowelsF --> u
VowelsF --> y
VowelsF --> )
VowelsF --> e
VowelsF --> |
VowelsF --> o
VowelsF --> I
VowelsF --> Y
VowelsF --> E
VowelsF --> /
VowelsF --> &
VowelsF --> O
VowelsF --> U
VowelsF --> @
Syll --> i
Syll --> a
Syll --> u
Syll --> y
Syll --> )
Syll --> e
Syll --> |
Syll --> o
Syll --> I
Syll --> Y
Syll --> E
Syll --> /
Syll --> &
Syll --> O
Syll --> U
Syll --> @
ConsonantI --> p
ConsonantI --> b
ConsonantI --> t
ConsonantI --> d
ConsonantI --> k
ConsonantI --> g
ConsonantI --> N
ConsonantI --> m
ConsonantI --> n
ConsonantI --> l
ConsonantI --> r
ConsonantI --> f
ConsonantI --> v
ConsonantI --> s
ConsonantI --> z
ConsonantI --> S
ConsonantI --> j
ConsonantI --> x
ConsonantI --> h
ConsonantI --> +
ConsonantI --> =
ConsonantI --> J
ConsonantI --> Z
ConsonantF --> p
ConsonantF --> b
ConsonantF --> t
ConsonantF --> d
ConsonantF --> k
ConsonantF --> g
ConsonantF --> N
ConsonantF --> m
ConsonantF --> n
ConsonantF --> l
ConsonantF --> r
ConsonantF --> f
ConsonantF --> v
ConsonantF --> s
ConsonantF --> z
ConsonantF --> S
ConsonantF --> j
ConsonantF --> x
ConsonantF --> h
ConsonantF --> +
ConsonantF --> =
ConsonantF --> J
ConsonantF --> Z
Vowel --> i
Vowel --> a
Vowel --> u
Vowel --> y
Vowel --> )
Vowel --> e
Vowel --> |
Vowel --> o
Vowel --> I
Vowel --> Y
Vowel --> E
Vowel --> /
Vowel --> &
Vowel --> O
Vowel --> U
Vowel --> @
ConsonantsI --> p
ConsonantsI --> b
ConsonantsI --> t
ConsonantsI --> d
ConsonantsI --> k
ConsonantsI --> g
ConsonantsI --> N
ConsonantsI --> m
ConsonantsI --> n
ConsonantsI --> l
ConsonantsI --> r
ConsonantsI --> f
ConsonantsI --> v
ConsonantsI --> s
ConsonantsI --> z
ConsonantsI --> S
ConsonantsI --> j
ConsonantsI --> x
ConsonantsI --> h
ConsonantsI --> +
ConsonantsI --> =
ConsonantsI --> J
ConsonantsI --> Z
ConsonantsF --> p
ConsonantsF --> b
ConsonantsF --> t
ConsonantsF --> d
ConsonantsF --> k
ConsonantsF --> g
ConsonantsF --> N
ConsonantsF --> m
ConsonantsF --> n
ConsonantsF --> l
ConsonantsF --> r
ConsonantsF --> f
ConsonantsF --> v
ConsonantsF --> s
ConsonantsF --> z
ConsonantsF --> S
ConsonantsF --> j
ConsonantsF --> x
ConsonantsF --> h
ConsonantsF --> +
ConsonantsF --> =
ConsonantsF --> J
ConsonantsF --> Z
Vowels --> i
Vowels --> a
Vowels --> u
Vowels --> y
Vowels --> )
Vowels --> e
Vowels --> |
Vowels --> o
Vowels --> I
Vowels --> Y
Vowels --> E
Vowels --> /
Vowels --> &
Vowels --> O
Vowels --> U
Vowels --> @
SyllI --> i
SyllI --> a
SyllI --> u
SyllI --> y
SyllI --> )
SyllI --> e
SyllI --> |
SyllI --> o
SyllI --> I
SyllI --> Y
SyllI --> E
SyllI --> /
SyllI --> &
SyllI --> O
SyllI --> U
SyllI --> @
SyllF --> i
SyllF --> a
SyllF --> u
SyllF --> y
SyllF --> )
SyllF --> e
SyllF --> |
SyllF --> o
SyllF --> I
SyllF --> Y
SyllF --> E
SyllF --> /
SyllF --> &
SyllF --> O
SyllF --> U
SyllF --> @
ConsonantO --> p
ConsonantO --> b
ConsonantO --> t
ConsonantO --> d
ConsonantO --> k
ConsonantO --> g
ConsonantO --> N
ConsonantO --> m
ConsonantO --> n
ConsonantO --> l
ConsonantO --> r
ConsonantO --> f
ConsonantO --> v
ConsonantO --> s
ConsonantO --> z
ConsonantO --> S
ConsonantO --> j
ConsonantO --> x
ConsonantO --> h
ConsonantO --> +
ConsonantO --> =
ConsonantO --> J
ConsonantO --> Z
ConsonantC --> p
ConsonantC --> b
ConsonantC --> t
ConsonantC --> d
ConsonantC --> k
ConsonantC --> g
ConsonantC --> N
ConsonantC --> m
ConsonantC --> n
ConsonantC --> l
ConsonantC --> r
ConsonantC --> f
ConsonantC --> v
ConsonantC --> s
ConsonantC --> z
ConsonantC --> S
ConsonantC --> j
ConsonantC --> x
ConsonantC --> h
ConsonantC --> +
ConsonantC --> =
ConsonantC --> J
ConsonantC --> Z
ConsonantsO --> p
ConsonantsO --> b
ConsonantsO --> t
ConsonantsO --> d
ConsonantsO --> k
ConsonantsO --> g
ConsonantsO --> N
ConsonantsO --> m
ConsonantsO --> n
ConsonantsO --> l
ConsonantsO --> r
ConsonantsO --> f
ConsonantsO --> v
ConsonantsO --> s
ConsonantsO --> z
ConsonantsO --> S
ConsonantsO --> j
ConsonantsO --> x
ConsonantsO --> h
ConsonantsO --> +
ConsonantsO --> =
ConsonantsO --> J
ConsonantsO --> Z
ConsonantsC --> p
ConsonantsC --> b
ConsonantsC --> t
ConsonantsC --> d
ConsonantsC --> k
ConsonantsC --> g
ConsonantsC --> N
ConsonantsC --> m
ConsonantsC --> n
ConsonantsC --> l
ConsonantsC --> r
ConsonantsC --> f
ConsonantsC --> v
ConsonantsC --> s
ConsonantsC --> z
ConsonantsC --> S
ConsonantsC --> j
ConsonantsC --> x
ConsonantsC --> h
ConsonantsC --> +
ConsonantsC --> =
ConsonantsC --> J
ConsonantsC --> Z