Word --> ConsonantsI VowelsF
Word --> ConsonantsI RhymeF
Word --> Vowels ConsonantsF
Word --> SyllI Sylls
Word --> Vowel Vowels
Sylls --> SepSyll Sylls
Sylls --> Separator SyllF
SepSyll --> Separator Syll
Syll --> Vowel Vowels
Syll --> Vowels ConsonantsC
Syll --> ConsonantsO Vowels
Syll --> ConsonantsO Rhyme
SyllI --> ConsonantsI Vowels
SyllI --> ConsonantsI Rhyme
SyllI --> Vowel Vowels
SyllI --> Vowels ConsonantsC
SyllF --> Vowels ConsonantsF
SyllF --> Vowel Vowels
SyllF --> ConsonantsO VowelsF
SyllF --> ConsonantsO RhymeF
Rhyme --> Vowels ConsonantsC
RhymeF --> Vowels ConsonantsF
VowelsF --> VowelF VowelsF
Vowels --> Vowel Vowels
ConsonantsI --> ConsonantI ConsonantsI
ConsonantsO --> ConsonantO ConsonantsO
ConsonantsC --> ConsonantC ConsonantsC
ConsonantsF --> ConsonantF ConsonantsF
Separator --> -
Word --> i
Word --> y
Word --> e
Word --> |
Word --> a
Word --> o
Word --> u
Word --> I
Word --> E
Word --> A
Word --> O
Word --> }
Word --> @
Word --> L
Word --> M
Word --> )
VowelF --> i
VowelF --> y
VowelF --> e
VowelF --> |
VowelF --> a
VowelF --> o
VowelF --> u
VowelF --> I
VowelF --> E
VowelF --> A
VowelF --> O
VowelF --> }
VowelF --> @
VowelF --> L
VowelF --> M
VowelF --> )
VowelsF --> i
VowelsF --> y
VowelsF --> e
VowelsF --> |
VowelsF --> a
VowelsF --> o
VowelsF --> u
VowelsF --> I
VowelsF --> E
VowelsF --> A
VowelsF --> O
VowelsF --> }
VowelsF --> @
VowelsF --> L
VowelsF --> M
VowelsF --> )
Syll --> i
Syll --> y
Syll --> e
Syll --> |
Syll --> a
Syll --> o
Syll --> u
Syll --> I
Syll --> E
Syll --> A
Syll --> O
Syll --> }
Syll --> @
Syll --> L
Syll --> M
Syll --> )
ConsonantI --> p
ConsonantI --> b
ConsonantI --> t
ConsonantI --> d
ConsonantI --> k
ConsonantI --> g
ConsonantI --> N
ConsonantI --> m
ConsonantI --> n
ConsonantI --> l
ConsonantI --> r
ConsonantI --> f
ConsonantI --> v
ConsonantI --> s
ConsonantI --> z
ConsonantI --> S
ConsonantI --> j
ConsonantI --> x
ConsonantI --> h
ConsonantI --> G
ConsonantI --> w
ConsonantI --> Z
ConsonantF --> p
ConsonantF --> b
ConsonantF --> t
ConsonantF --> d
ConsonantF --> k
ConsonantF --> g
ConsonantF --> N
ConsonantF --> m
ConsonantF --> n
ConsonantF --> l
ConsonantF --> r
ConsonantF --> f
ConsonantF --> v
ConsonantF --> s
ConsonantF --> z
ConsonantF --> S
ConsonantF --> j
ConsonantF --> x
ConsonantF --> h
ConsonantF --> G
ConsonantF --> w
ConsonantF --> Z
Vowel --> i
Vowel --> y
Vowel --> e
Vowel --> |
Vowel --> a
Vowel --> o
Vowel --> u
Vowel --> I
Vowel --> E
Vowel --> A
Vowel --> O
Vowel --> }
Vowel --> @
Vowel --> L
Vowel --> M
Vowel --> )
ConsonantsI --> p
ConsonantsI --> b
ConsonantsI --> t
ConsonantsI --> d
ConsonantsI --> k
ConsonantsI --> g
ConsonantsI --> N
ConsonantsI --> m
ConsonantsI --> n
ConsonantsI --> l
ConsonantsI --> r
ConsonantsI --> f
ConsonantsI --> v
ConsonantsI --> s
ConsonantsI --> z
ConsonantsI --> S
ConsonantsI --> j
ConsonantsI --> x
ConsonantsI --> h
ConsonantsI --> G
ConsonantsI --> w
ConsonantsI --> Z
ConsonantsF --> p
ConsonantsF --> b
ConsonantsF --> t
ConsonantsF --> d
ConsonantsF --> k
ConsonantsF --> g
ConsonantsF --> N
ConsonantsF --> m
ConsonantsF --> n
ConsonantsF --> l
ConsonantsF --> r
ConsonantsF --> f
ConsonantsF --> v
ConsonantsF --> s
ConsonantsF --> z
ConsonantsF --> S
ConsonantsF --> j
ConsonantsF --> x
ConsonantsF --> h
ConsonantsF --> G
ConsonantsF --> w
ConsonantsF --> Z
Vowels --> i
Vowels --> y
Vowels --> e
Vowels --> |
Vowels --> a
Vowels --> o
Vowels --> u
Vowels --> I
Vowels --> E
Vowels --> A
Vowels --> O
Vowels --> }
Vowels --> @
Vowels --> L
Vowels --> M
Vowels --> )
SyllI --> i
SyllI --> y
SyllI --> e
SyllI --> |
SyllI --> a
SyllI --> o
SyllI --> u
SyllI --> I
SyllI --> E
SyllI --> A
SyllI --> O
SyllI --> }
SyllI --> @
SyllI --> L
SyllI --> M
SyllI --> )
SyllF --> i
SyllF --> y
SyllF --> e
SyllF --> |
SyllF --> a
SyllF --> o
SyllF --> u
SyllF --> I
SyllF --> E
SyllF --> A
SyllF --> O
SyllF --> }
SyllF --> @
SyllF --> L
SyllF --> M
SyllF --> )
ConsonantO --> p
ConsonantO --> b
ConsonantO --> t
ConsonantO --> d
ConsonantO --> k
ConsonantO --> g
ConsonantO --> N
ConsonantO --> m
ConsonantO --> n
ConsonantO --> l
ConsonantO --> r
ConsonantO --> f
ConsonantO --> v
ConsonantO --> s
ConsonantO --> z
ConsonantO --> S
ConsonantO --> j
ConsonantO --> x
ConsonantO --> h
ConsonantO --> G
ConsonantO --> w
ConsonantO --> Z
ConsonantC --> p
ConsonantC --> b
ConsonantC --> t
ConsonantC --> d
ConsonantC --> k
ConsonantC --> g
ConsonantC --> N
ConsonantC --> m
ConsonantC --> n
ConsonantC --> l
ConsonantC --> r
ConsonantC --> f
ConsonantC --> v
ConsonantC --> s
ConsonantC --> z
ConsonantC --> S
ConsonantC --> j
ConsonantC --> x
ConsonantC --> h
ConsonantC --> G
ConsonantC --> w
ConsonantC --> Z
ConsonantsO --> p
ConsonantsO --> b
ConsonantsO --> t
ConsonantsO --> d
ConsonantsO --> k
ConsonantsO --> g
ConsonantsO --> N
ConsonantsO --> m
ConsonantsO --> n
ConsonantsO --> l
ConsonantsO --> r
ConsonantsO --> f
ConsonantsO --> v
ConsonantsO --> s
ConsonantsO --> z
ConsonantsO --> S
ConsonantsO --> j
ConsonantsO --> x
ConsonantsO --> h
ConsonantsO --> G
ConsonantsO --> w
ConsonantsO --> Z
ConsonantsC --> p
ConsonantsC --> b
ConsonantsC --> t
ConsonantsC --> d
ConsonantsC --> k
ConsonantsC --> g
ConsonantsC --> N
ConsonantsC --> m
ConsonantsC --> n
ConsonantsC --> l
ConsonantsC --> r
ConsonantsC --> f
ConsonantsC --> v
ConsonantsC --> s
ConsonantsC --> z
ConsonantsC --> S
ConsonantsC --> j
ConsonantsC --> x
ConsonantsC --> h
ConsonantsC --> G
ConsonantsC --> w
ConsonantsC --> Z